
const {createClient}=supabase;const sb=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);let cache={products:[],suppliers:[],customers:[]};
const menus=[['dashboard','📊 Dashboard'],['master','⚙️ Master Data'],['pembelian','🐟 Pembelian'],['produksi','🏭 Produksi'],['penjualan','💰 Penjualan'],['kas','💵 Kas'],['biaya','🧾 Biaya'],['laporan','📑 Laporan']];
function rupiah(x){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(x)||0)}function n(x){return Number(x)||0}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function today(){return new Date().toISOString().slice(0,10)}function msg(t){alert(t)}
function initNav(){let html=menus.map(([k,t])=>`<button data-page="${k}" onclick="page('${k}',this)">${t}</button>`).join('');sideNav.innerHTML=html;mobileNav.innerHTML=html}
async function signIn(){const {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error){loginmsg.textContent=error.message;loginmsg.classList.remove('hide')}else await start()}async function signOut(){await sb.auth.signOut();location.reload()}
async function start(){login.classList.add('hide');app.classList.remove('hide');initNav();await loadMasters();await page('dashboard')}
async function loadMasters(){let [a,b,c]=await Promise.all([sb.from('products').select('*').order('name'),sb.from('suppliers').select('*').order('name'),sb.from('customers').select('*').order('name')]);cache.products=a.data||[];cache.suppliers=b.data||[];cache.customers=c.data||[]}
function sel(arr,name,label='Pilih...'){return `<select name="${name}" required><option value="">${label}</option>${arr.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`}
async function page(p,el){document.querySelectorAll('nav button,.mobilebar button').forEach(x=>x.classList.remove('active'));document.querySelectorAll(`[data-page="${p}"]`).forEach(x=>x.classList.add('active'));await loadMasters();if(p==='dashboard')dashboard();if(p==='master')master();if(p==='pembelian')purchases();if(p==='produksi')production();if(p==='penjualan')sales();if(p==='kas')cash();if(p==='biaya')costs();if(p==='laporan')report()}
async function getRows(table,fields='*'){let {data,error}=await sb.from(table).select(fields);return error?[]:(data||[])}
async function dashboard(){let [buys,salesRows,prods,cashRows]=await Promise.all([getRows('purchases','purchase_date,product_id,weight_kg,total_amount'),getRows('sales','sale_date,product_id,weight_kg,total_amount'),getRows('production','production_date,product_id,input_weight_kg,output_weight_kg,total_production_cost,overhead_allocated'),getRows('cash_transactions','transaction_type,amount')]);let buy=buys.reduce((a,x)=>a+n(x.total_amount),0),sale=salesRows.reduce((a,x)=>a+n(x.total_amount),0),out=prods.reduce((a,x)=>a+n(x.output_weight_kg),0),cashv=cashRows.reduce((a,x)=>a+(x.transaction_type==='masuk'?n(x.amount):-n(x.amount)),0);let raw=buys.reduce((a,x)=>a+n(x.weight_kg),0)-prods.reduce((a,x)=>a+n(x.input_weight_kg),0),finished=out-salesRows.reduce((a,x)=>a+n(x.weight_kg),0);let pc=prods.reduce((a,x)=>a+n(x.total_production_cost)+n(x.overhead_allocated),0),profit=sale-pc;
content.innerHTML=`<h1>Dashboard</h1><div class="grid"><div class="card"><div class="statlabel">Total Pembelian</div><div class="big">${rupiah(buy)}</div></div><div class="card"><div class="statlabel">Total Penjualan</div><div class="big">${rupiah(sale)}</div></div><div class="card"><div class="statlabel">Produksi Jadi</div><div class="big">${out.toLocaleString('id-ID')} kg</div></div><div class="card"><div class="statlabel">Kas Bersih</div><div class="big">${rupiah(cashv)}</div></div></div><div class="grid" style="margin-top:14px"><div class="card"><div class="statlabel">Estimasi Stok Bahan Baku</div><div class="big">${raw.toLocaleString('id-ID',{maximumFractionDigits:2})} kg</div></div><div class="card"><div class="statlabel">Estimasi Stok Produk Jadi</div><div class="big">${finished.toLocaleString('id-ID',{maximumFractionDigits:2})} kg</div></div><div class="card"><div class="statlabel">Biaya Produksi</div><div class="big">${rupiah(pc)}</div></div><div class="card"><div class="statlabel">Selisih Penjualan - Biaya Produksi</div><div class="big ${profit>=0?'positive':'negative'}">${rupiah(profit)}</div></div></div><div class="notice" style="margin-top:14px"><b>Catatan stok:</b> stok di dashboard dihitung dari transaksi pembelian, produksi, dan penjualan. Ini adalah stok operasional dan belum memperhitungkan retur/penyesuaian stok manual.</div>`}
async function master(){content.innerHTML=`<h1>Master Data</h1><div class="notice"><b>Koreksi data:</b> gunakan tombol <b>Hapus</b> pada data yang salah, lalu input ulang data yang benar. Penghapusan membutuhkan konfirmasi.</div><div class="grid2"><form onsubmit="addSupplier(event)"><h2>Supplier</h2><div class="fields"><div><label>Nama</label><input name="name" required></div><div><label>No. HP</label><input name="phone"></div><div><label>Alamat</label><input name="address"></div></div><button class="btn" style="margin-top:12px">Simpan Supplier</button></form><form onsubmit="addCustomer(event)"><h2>Customer</h2><div class="fields"><div><label>Nama</label><input name="name" required></div><div><label>No. HP</label><input name="phone"></div><div><label>Alamat</label><input name="address"></div></div><button class="btn" style="margin-top:12px">Simpan Customer</button></form></div><form onsubmit="addProduct(event)" style="margin-top:14px"><h2>Produk / Jenis Ikan</h2><div class="fields"><div><label>Nama produk</label><input name="name" placeholder="Ikan Layang" required></div><div><label>Kategori</label><select name="category"><option value="bahan_baku">Bahan baku</option><option value="produk_jadi">Produk jadi</option><option value="bahan_penolong">Bahan penolong</option></select></div><div><label>Harga default/kg</label><input name="price" type="number" value="0"></div></div><button class="btn" style="margin-top:12px">Simpan Produk</button></form><div class="grid2" style="margin-top:14px"><div class="card"><h2>Produk tersimpan</h2>${simpleList(cache.products,['name','category','default_price'], 'products')}</div><div class="card"><h2>Supplier tersimpan</h2>${simpleList(cache.suppliers,['name','phone'], 'suppliers')}</div></div><div class="card" style="margin-top:14px"><h2>Customer tersimpan</h2>${simpleList(cache.customers,['name','phone'], 'customers')}</div>`}

async function addSupplier(e){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('suppliers').insert({name:f.get('name'),phone:f.get('phone'),address:f.get('address')});if(error)msg(error.message);else{msg('Supplier tersimpan');master()}}async function addCustomer(e){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('customers').insert({name:f.get('name'),phone:f.get('phone'),address:f.get('address')});if(error)msg(error.message);else{msg('Customer tersimpan');master()}}async function addProduct(e){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('products').insert({name:f.get('name'),category:f.get('category'),default_price:n(f.get('price'))});if(error)msg(error.message);else{msg('Produk tersimpan');master()}}
async function purchases(){content.innerHTML=`<h1>Pembelian Bahan Baku</h1><form onsubmit="savePurchase(event)"><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Supplier</label>${sel(cache.suppliers,'supplier_id')}</div><div><label>Jenis ikan</label>${sel(cache.products.filter(x=>x.category==='bahan_baku'),'product_id')}</div><div><label>Berat (kg)</label><input name="weight" type="number" step=".01" required></div><div><label>Harga/kg</label><input name="price" type="number" required></div><div><label>Status pembayaran</label><select name="status"><option value="lunas">Lunas</option><option value="hutang">Hutang</option><option value="sebagian">Sebagian</option></select></div></div><button class="btn" style="margin-top:12px">Simpan Pembelian</button></form><div id="tbl"></div>`;let {data,error}=await sb.from('purchases').select('id,purchase_date,weight_kg,price_per_kg,total_amount,payment_status,products(name),suppliers(name)').order('purchase_date',{ascending:false}).limit(100);tbl.innerHTML=table(data||[],['purchase_date','suppliers.name','products.name','weight_kg','price_per_kg','total_amount','payment_status'],error,'purchases')}
async function savePurchase(e){e.preventDefault();let f=new FormData(e.target),x={purchase_date:f.get('date'),supplier_id:f.get('supplier_id'),product_id:f.get('product_id'),weight_kg:n(f.get('weight')),price_per_kg:n(f.get('price')),payment_status:f.get('status')};let {error}=await sb.from('purchases').insert(x);if(error)msg(error.message);else{msg('Pembelian tersimpan');purchases()}}
async function production(){let finished=cache.products.filter(x=>x.category==='produk_jadi');content.innerHTML=`<h1>Produksi / Pengeringan</h1><div class="notice"><b>Contoh:</b> ikan basah 1.000 kg → hasil jadi 600 kg. Sistem menghitung penyusutan dari berat input dan output.</div><form onsubmit="saveProduction(event)"><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Produk jadi</label>${sel(finished,'product_id')}</div><div><label>Bahan baku (kg)</label><input name="input" type="number" step=".01" required></div><div><label>Hasil jadi (kg)</label><input name="output" type="number" step=".01" required></div><div><label>Garam</label><input name="salt" type="number" value="0"></div><div><label>Tenaga kerja</label><input name="labor" type="number" value="0"></div><div><label>Biaya lain</label><input name="other" type="number" value="0"></div></div><button class="btn" style="margin-top:12px">Simpan Produksi</button></form><div id="tbl"></div>`;let {data,error}=await sb.from('production').select('id,production_date,input_weight_kg,output_weight_kg,total_production_cost,overhead_allocated,shrinkage_percent,products(name)').order('production_date',{ascending:false}).limit(100);tbl.innerHTML=table(data||[],['production_date','products.name','input_weight_kg','output_weight_kg','shrinkage_percent','total_production_cost','overhead_allocated'],error,'production')}
async function saveProduction(e){e.preventDefault();let f=new FormData(e.target),input=n(f.get('input')),output=n(f.get('output'));if(output>input){msg('Hasil jadi tidak boleh lebih besar dari bahan baku.');return}let x={production_date:f.get('date'),product_id:f.get('product_id'),input_weight_kg:input,output_weight_kg:output,salt_cost:n(f.get('salt')),labor_cost:n(f.get('labor')),other_cost:n(f.get('other'))};let {error}=await sb.from('production').insert(x);if(error)msg(error.message);else{msg('Produksi tersimpan');production()}}
async function sales(){let finished=cache.products.filter(x=>x.category==='produk_jadi');content.innerHTML=`<h1>Penjualan</h1><form onsubmit="saveSale(event)"><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Customer</label>${sel(cache.customers,'customer_id')}</div><div><label>Produk</label>${sel(finished,'product_id')}</div><div><label>Berat (kg)</label><input name="weight" type="number" step=".01" required></div><div><label>Harga/kg</label><input name="price" type="number" required></div><div><label>Status pembayaran</label><select name="status"><option value="lunas">Lunas</option><option value="piutang">Piutang</option><option value="sebagian">Sebagian</option></select></div></div><button class="btn" style="margin-top:12px">Simpan Penjualan</button></form><div id="tbl"></div>`;let {data,error}=await sb.from('sales').select('id,sale_date,weight_kg,price_per_kg,total_amount,payment_status,products(name),customers(name)').order('sale_date',{ascending:false}).limit(100);tbl.innerHTML=table(data||[],['sale_date','customers.name','products.name','weight_kg','price_per_kg','total_amount','payment_status'],error,'sales')}
async function saveSale(e){e.preventDefault();let f=new FormData(e.target),x={sale_date:f.get('date'),customer_id:f.get('customer_id'),product_id:f.get('product_id'),weight_kg:n(f.get('weight')),price_per_kg:n(f.get('price')),payment_status:f.get('status')};let {error}=await sb.from('sales').insert(x);if(error)msg(error.message);else{msg('Penjualan tersimpan');sales()}}
async function cash(){content.innerHTML=`<h1>Kas</h1><form onsubmit="saveCash(event)"><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Jenis</label><select name="type"><option value="masuk">Kas masuk</option><option value="keluar">Kas keluar</option></select></div><div><label>Kategori</label><input name="category" placeholder="Penjualan / listrik / transport" required></div><div><label>Nominal</label><input name="amount" type="number" required></div><div><label>Keterangan</label><input name="note"></div></div><button class="btn" style="margin-top:12px">Simpan Kas</button></form><div id="tbl"></div>`;let {data,error}=await sb.from('cash_transactions').select('*').order('transaction_date',{ascending:false}).limit(100);tbl.innerHTML=table(data||[],['transaction_date','transaction_type','category','amount','reference','notes'],error,'cash_transactions')}
async function saveCash(e){e.preventDefault();let f=new FormData(e.target),x={transaction_date:f.get('date'),transaction_type:f.get('type'),category:f.get('category'),amount:n(f.get('amount')),notes:f.get('note')};let {error}=await sb.from('cash_transactions').insert(x);if(error)msg(error.message);else{msg('Kas tersimpan');cash()}}
async function costs(){
let [emps,salt,elec,pay,other]=await Promise.all([
 sb.from('employees').select('*').order('name'),sb.from('salt_purchases').select('*').order('purchase_date',{ascending:false}),
 sb.from('electricity_expenses').select('*').order('week_start',{ascending:false}),sb.from('employee_daily_payments').select('*,employees(name)').order('payment_date',{ascending:false}),sb.from('other_expenses').select('*').order('expense_date',{ascending:false})]);
let E=emps.data||[],S=salt.data||[],L=elec.data||[],P=pay.data||[],O=other.data||[]; cacheEmp=E;
content.innerHTML=`<h1>Biaya Operasional</h1>
<div class="notice"><b>Tahap 2:</b> biaya garam dicatat bulanan, listrik mingguan, pegawai harian, dan biaya lain. Biaya periode dapat dialokasikan otomatis ke batch produksi berdasarkan <b>berat output (kg)</b>.</div>
<div class="grid2">
<form onsubmit="addEmployee(event)"><h2>👷 Pegawai</h2><div class="fields"><div><label>Nama</label><input name="name" required></div><div><label>Jabatan</label><input name="position"></div><div><label>Upah/hari</label><input name="wage" type="number" required></div></div><button class="btn">Simpan Pegawai</button></form>
<form onsubmit="addSalt(event)"><h2>🧂 Pembelian Garam Bulanan</h2><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Supplier</label><input name="supplier"></div><div><label>Jumlah (kg)</label><input name="qty" type="number" step=".01" required></div><div><label>Harga/kg</label><input name="price" type="number" required></div><div><label>Status</label><select name="status"><option>lunas</option><option>hutang</option><option>sebagian</option></select></div></div><button class="btn">Simpan Garam</button></form>
<form onsubmit="addElec(event)"><h2>⚡ Listrik Mingguan</h2><div class="fields"><div><label>Mulai</label><input name="start" type="date" value="${today()}" required></div><div><label>Selesai</label><input name="end" type="date" value="${today()}" required></div><div><label>Nominal</label><input name="amount" type="number" required></div></div><button class="btn">Simpan Listrik</button></form>
<form onsubmit="addPay(event)"><h2>👷 Pembayaran Pegawai Harian</h2><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Pegawai</label><select name="employee" required><option value="">Pilih...</option>${E.filter(x=>x.active).map(x=>`<option value="${x.id}">${esc(x.name)} — ${rupiah(x.daily_wage)}</option>`).join('')}</select></div><div><label>Hari</label><input name="days" type="number" step=".5" value="1" required></div><div><label>Lembur</label><input name="ot" type="number" value="0"></div><div><label>Bonus</label><input name="bonus" type="number" value="0"></div></div><button class="btn">Simpan Upah</button></form>
<form onsubmit="addOther(event)" style="grid-column:1/-1"><h2>📦 Biaya Lain</h2><div class="fields"><div><label>Tanggal</label><input name="date" type="date" value="${today()}" required></div><div><label>Kategori</label><input name="category" placeholder="BBM / kemasan / air / perawatan" required></div><div><label>Nominal</label><input name="amount" type="number" required></div><div><label>Keterangan</label><input name="notes"></div></div><button class="btn">Simpan Biaya</button></form></div>
<div class="card" style="margin-top:14px"><h2>⚙️ Alokasi Biaya ke Produksi</h2><div class="notice">Sistem menjumlahkan biaya pada periode tersebut lalu membaginya ke batch produksi berdasarkan proporsi <b>output kg</b>. Jika alokasi dijalankan lagi untuk bulan yang sama, alokasi lama akan diganti dengan perhitungan terbaru.</div><form onsubmit="allocateCosts(event)"><div class="fields"><div><label>Bulan</label><input name="month" type="month" value="${today().slice(0,7)}" required></div></div><button class="btn">Hitung & Alokasikan</button></form><div id="allocationResult" class="msg hide"></div></div>
<div class="grid" style="margin-top:14px"><div class="card"><div class="statlabel">Total Garam</div><div class="big">${rupiah(S.reduce((a,x)=>a+n(x.total_amount),0))}</div></div><div class="card"><div class="statlabel">Total Listrik</div><div class="big">${rupiah(L.reduce((a,x)=>a+n(x.amount),0))}</div></div><div class="card"><div class="statlabel">Total Pegawai</div><div class="big">${rupiah(P.reduce((a,x)=>a+n(x.total_amount),0))}</div></div><div class="card"><div class="statlabel">Biaya Lain</div><div class="big">${rupiah(O.reduce((a,x)=>a+n(x.amount),0))}</div></div></div>
<h2 style="margin-top:22px">Daftar Biaya</h2>${table(S,['purchase_date','supplier_name','quantity_kg','price_per_kg','total_amount','payment_status'],null,'salt_purchases')}${table(L,['week_start','week_end','amount','notes'],null,'electricity_expenses')}${table(P,['payment_date','employees.name','days','wage','overtime','bonus','total_amount'],null,'employee_daily_payments')}${table(O,['expense_date','category','amount','notes'],null,'other_expenses')}
<h2 style="margin-top:22px">Daftar Pegawai</h2>${table(E,['name','position','daily_wage','active'],null,'employees')}`;
}
function errorSafe(x){return x}
async function allocateCosts(e){
e.preventDefault();let f=new FormData(e.target),month=f.get('month');if(!month)return;
let start=month+'-01', end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10);
let [salt,elec,pay,other,prod]=await Promise.all([
 sb.from('salt_purchases').select('id,total_amount,purchase_date').gte('purchase_date',start).lte('purchase_date',end),
 sb.from('electricity_expenses').select('id,amount,week_start,week_end').gte('week_start',start).lte('week_start',end),
 sb.from('employee_daily_payments').select('id,total_amount,payment_date').gte('payment_date',start).lte('payment_date',end),
 sb.from('other_expenses').select('id,amount,expense_date').gte('expense_date',start).lte('expense_date',end),
 sb.from('production').select('id,production_date,output_weight_kg,total_production_cost').gte('production_date',start).lte('production_date',end)
]);
for(const r of [salt,elec,pay,other,prod])if(r.error){msg('Gagal membaca data: '+r.error.message);return}
let rows=prod.data||[], totalOutput=rows.reduce((a,x)=>a+n(x.output_weight_kg),0);
if(!rows.length||totalOutput<=0){msg('Belum ada batch produksi dengan output > 0 pada bulan tersebut.');return}
let totals={garam:(salt.data||[]).reduce((a,x)=>a+n(x.total_amount),0),listrik:(elec.data||[]).reduce((a,x)=>a+n(x.amount),0),pegawai:(pay.data||[]).reduce((a,x)=>a+n(x.total_amount),0),lain:(other.data||[]).reduce((a,x)=>a+n(x.amount),0)};
let {error:delErr}=await sb.from('production_cost_allocations').delete().eq('period_month',start);if(delErr){msg('Gagal menghapus alokasi lama: '+delErr.message);return}
let inserts=[];for(const r of rows){let share=n(r.output_weight_kg)/totalOutput;for(const type of Object.keys(totals)){if(totals[type]<=0)continue;inserts.push({period_month:start,production_id:r.id,cost_type:type,source_amount:totals[type],allocated_amount:totals[type]*share,allocation_weight_kg:n(r.output_weight_kg),method:'proporsional_output'});}}
if(inserts.length){let {error}=await sb.from('production_cost_allocations').insert(inserts);if(error){msg('Gagal menyimpan alokasi: '+error.message);return}}
for(const r of rows){let allocated=inserts.filter(x=>x.production_id===r.id).reduce((a,x)=>a+n(x.allocated_amount),0);let {error}=await sb.from('production').update({overhead_allocated:allocated}).eq('id',r.id);if(error){msg('Alokasi tersimpan, tetapi gagal memperbarui batch: '+error.message);return}}
let total=Object.values(totals).reduce((a,x)=>a+x,0);let box=document.getElementById('allocationResult');box.textContent=`Alokasi ${month} selesai. Total biaya dialokasikan ${rupiah(total)} ke ${rows.length} batch produksi.`;box.classList.remove('hide');msg('Alokasi biaya berhasil');production();
}
async function addEmployee(e){e.preventDefault();let f=new FormData(e.target),{error}=await sb.from('employees').insert({name:f.get('name'),position:f.get('position'),daily_wage:n(f.get('wage'))});if(error)msg(error.message);else{msg('Pegawai tersimpan');costs()}}
async function addSalt(e){e.preventDefault();let f=new FormData(e.target),{error}=await sb.from('salt_purchases').insert({purchase_date:f.get('date'),supplier_name:f.get('supplier'),quantity_kg:n(f.get('qty')),price_per_kg:n(f.get('price')),payment_status:f.get('status')});if(error)msg(error.message);else{msg('Pembelian garam tersimpan');costs()}}
async function addElec(e){e.preventDefault();let f=new FormData(e.target),{error}=await sb.from('electricity_expenses').insert({week_start:f.get('start'),week_end:f.get('end'),amount:n(f.get('amount'))});if(error)msg(error.message);else{msg('Biaya listrik tersimpan');costs()}}
async function addPay(e){e.preventDefault();let f=new FormData(e.target),emp=cacheEmp.find(x=>x.id===f.get('employee'));let {error}=await sb.from('employee_daily_payments').insert({payment_date:f.get('date'),employee_id:f.get('employee'),days:n(f.get('days')),wage:n(emp?.daily_wage),overtime:n(f.get('ot')),bonus:n(f.get('bonus'))});if(error)msg(error.message);else{msg('Upah tersimpan');costs()}}
async function addOther(e){e.preventDefault();let f=new FormData(e.target),{error}=await sb.from('other_expenses').insert({expense_date:f.get('date'),category:f.get('category'),amount:n(f.get('amount')),notes:f.get('notes')});if(error)msg(error.message);else{msg('Biaya tersimpan');costs()}}
let cacheEmp=[];
async function report(){let [b,s,p,e]=await Promise.all([getRows('purchases','total_amount,weight_kg,price_per_kg'),getRows('sales','total_amount,weight_kg,price_per_kg'),getRows('production','total_production_cost,overhead_allocated,output_weight_kg'),getRows('expenses','amount')]);let buy=b.reduce((a,x)=>a+n(x.total_amount),0),sale=s.reduce((a,x)=>a+n(x.total_amount),0),pc=p.reduce((a,x)=>a+n(x.total_production_cost)+n(x.overhead_allocated),0),ex=e.reduce((a,x)=>a+n(x.amount),0),output=p.reduce((a,x)=>a+n(x.output_weight_kg),0),hpp=output?pc/output:0;content.innerHTML=`<h1>Laporan</h1><div class="grid"><div class="card"><div class="statlabel">Pembelian</div><div class="big">${rupiah(buy)}</div></div><div class="card"><div class="statlabel">Penjualan</div><div class="big">${rupiah(sale)}</div></div><div class="card"><div class="statlabel">Biaya Produksi</div><div class="big">${rupiah(pc)}</div></div><div class="card"><div class="statlabel">HPP Produksi/kg</div><div class="big">${rupiah(hpp)}</div></div></div><div class="grid" style="margin-top:14px"><div class="card"><div class="statlabel">Biaya Operasional</div><div class="big">${rupiah(ex)}</div></div><div class="card"><div class="statlabel">Selisih Penjualan - Biaya Produksi</div><div class="big ${sale-pc>=0?'positive':'negative'}">${rupiah(sale-pc)}</div></div><div class="card"><div class="statlabel">Total Output Produksi</div><div class="big">${output.toLocaleString('id-ID')} kg</div></div><div class="card"><div class="statlabel">Margin setelah biaya produksi</div><div class="big">${sale?((sale-pc)/sale*100).toFixed(1):0}%</div></div></div><div class="notice" style="margin-top:14px"><b>Penting:</b> HPP di sini adalah HPP biaya produksi yang sudah tercatat di tabel produksi. Agar HPP akuntansi benar-benar lengkap, harga ikan basah per batch dan biaya overhead perlu dimasukkan ke desain tahap berikutnya.</div>`}
function simpleList(rows,cols,tableName){if(!rows.length)return '<span class="muted">Belum ada data.</span>';return '<div class="tablewrap"><table><thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'<th>Aksi</th></tr></thead><tbody>'+rows.slice(0,100).map(r=>'<tr>'+cols.map(c=>`<td>${c.includes('price')?rupiah(r[c]):esc(r[c])}</td>`).join('')+`<td><button class="delete-btn" onclick="deleteRow('${tableName}','${r.id}')">Hapus</button></td></tr>`).join('')+'</tbody></table></div>'}
function table(rows,cols,error,tableName){if(error)return `<div class="notice">Gagal membaca data: ${esc(error.message)}</div>`;if(!rows.length)return '<div class="card"><span class="muted">Belum ada data.</span></div>';return '<div class="tablewrap"><table><thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'<th>Aksi</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>{let k=c.includes('.')?c.split('.')[0]:c,v=c.includes('.')?(r[k]?.name??''):r[k];let money=/amount|price|cost/.test(c);return `<td>${money?rupiah(v):esc(v)}</td>`}).join('')+`<td><button class="delete-btn" onclick="deleteRow('${tableName}','${r.id}')">Hapus</button></td></tr>`).join('')+'</tbody></table></div>'}
async function deleteRow(tableName,id){if(!id)return;if(!confirm('Hapus data ini? Tindakan ini tidak dapat dibatalkan.'))return;let {error}=await sb.from(tableName).delete().eq('id',id);if(error){msg('Data gagal dihapus: '+error.message);return}msg('Data berhasil dihapus');if(tableName==='purchases')purchases();else if(tableName==='production')production();else if(tableName==='sales')sales();else if(tableName==='cash_transactions')cash();else if(['products','suppliers','customers'].includes(tableName))master(); else if(['employees','salt_purchases','electricity_expenses','employee_daily_payments','other_expenses'].includes(tableName))costs()}
(async()=>{let {data}=await sb.auth.getSession();if(data.session)start()})();
